// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwclJc62yJwfPMuq50VDF6GC34mGW138',
    appId: '1:688861544662:web:064a07c6ecdb52267a0977',
    messagingSenderId: '688861544662',
    projectId: 'shohoz-rent',
    authDomain: 'shohoz-rent.firebaseapp.com',
    databaseURL: 'https://shohoz-rent-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shohoz-rent.firebasestorage.app',
    measurementId: 'G-L8JWYCKSQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9_FFOg9cXkR-X-StXp9xFVLHw9cjkAk',
    appId: '1:688861544662:android:44325d9bc4646b937a0977',
    messagingSenderId: '688861544662',
    projectId: 'shohoz-rent',
    databaseURL: 'https://shohoz-rent-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shohoz-rent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRb8XwkVNXz317s4Y4eOVjcYXsTue6NU',
    appId: '1:688861544662:ios:5a3f06c58830f67f7a0977',
    messagingSenderId: '688861544662',
    projectId: 'shohoz-rent',
    databaseURL: 'https://shohoz-rent-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shohoz-rent.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
